### ISSUE TITLE
Class File (or Parent) is missing method getExtension

### ISSUE THREAD

**Issue by dbatsche** [naucon/File#1]
#### Issue description

When using LogHandler, File gets loaded as dependency.
As soon as the class File is being loaded, a fatal error occurs:
`PHP Fatal error:  Class Naucon\File\File contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Naucon\File\FileInfoInterface::getExtension) in [...]/vendor/naucon/file/src/File.php on line 25`

Since I had an urgent issue at the moment, I made a workaround and implemented `getExtension` in `FileAbstract.php` myself (using `pathinfo()`).

*Side note*: `\SplFileInfo::getExtension()` was introduced with PHP 5.3.6 and is therefore missing in 5.3.3.

#### Steps to reproduce the issue

1. Use PHP 5.3.3
2. Load latest Nautic\Logger (using asterisk)
3. Use Nautic\Logger\LogHandler to log something.
4. Execute

#### What's the expected result?

- File should be loaded fine.

#### What's the actual result?

- `PHP Fatal error:  Class Naucon\File\File contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Naucon\File\FileInfoInterface::getExtension) in [...]/vendor/naucon/file/src/File.php on line 25`

**Comment by naucon** [comment]
Hi dbatsche,

thank you for contributing. I merged your PR f0049a8a4862463c97d8d3fe9622b051f070a7ea to fix the issue with PHP versions lower 5.3.6.
